.TH "/home/mike/projects/logic_calculator/contenteditor.h" 3 "Пн 28 Дек 2020" "Version 1.4" "Логический калькулятор" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mike/projects/logic_calculator/contenteditor.h
.SH SYNOPSIS
.br
.PP
\fC#include <QList>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QPlainTextEdit>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBContentEditor\fP"
.br
.RI "\fBContentEditor\fP - Класс отвечает за корректный и удобный вывод чего-либо в поле для вывода "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Логический калькулятор из исходного текста\&.
