.TH "/home/mike/projects/logic_calculator/inputeditor.cpp" 3 "Пн 28 Дек 2020" "Version 1.4" "Логический калькулятор" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mike/projects/logic_calculator/inputeditor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'inputeditor\&.h'\fP
.br
\fC#include <QString>\fP
.br

.SH "Автор"
.PP 
Автоматически создано Doxygen для Логический калькулятор из исходного текста\&.
