.TH "/home/mike/projects/logic_calculator/logic.cpp" 3 "Пн 28 Дек 2020" "Version 1.4" "Логический калькулятор" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mike/projects/logic_calculator/logic.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include 'logic\&.h'\fP
.br

.SH "Автор"
.PP 
Автоматически создано Doxygen для Логический калькулятор из исходного текста\&.
