.TH "/home/mike/projects/logic_calculator/main.cpp" 3 "Пн 28 Дек 2020" "Version 1.4" "Логический калькулятор" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mike/projects/logic_calculator/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include <QApplication>\fP
.br
\fC#include <QDebug>\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Функции"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Автор"
.PP 
Автоматически создано Doxygen для Логический калькулятор из исходного текста\&.
