.TH "/home/mike/projects/logic_calculator/README.md" 3 "Пн 28 Дек 2020" "Version 1.4" "Логический калькулятор" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mike/projects/logic_calculator/README.md
.SH SYNOPSIS
.br
.PP
.SH "Автор"
.PP 
Автоматически создано Doxygen для Логический калькулятор из исходного текста\&.
