.TH "/home/mike/projects/logic_calculator/variable.h" 3 "Пн 28 Дек 2020" "Version 1.4" "Логический калькулятор" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mike/projects/logic_calculator/variable.h
.SH SYNOPSIS
.br
.PP
\fC#include <QList>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QChar>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBVariable\fP"
.br
.RI "\fBVariable\fP - Класс логических переменных "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Логический калькулятор из исходного текста\&.
